export const RESPONSE_CODES = {
  SUCCESS: 0,

  INTERNAL_SERVER_ERROR: -1,

  INVALID_CREDS: 1,
  USER_NOT_FOUND: 2,
  USER_ALREADY_EXISTS: 3,
  BAD_REQUEST: 4,
  TOO_MANY_REQUESTS: 5,
  UNAUTHORIZED:6
} as const;
